
language: node_js
node_js:
    - "stable"
install:
    - npm install
addons:
    code_climate:
        repo_token: 3d8d02ae9e4d1360c2d7101b63f1b1e3ca26701f58bba8334e16e81b43f70dd0
script:
    - npm run coveralls
before_script:
  - npm install codeclimate-test-reporter istanbul -g
  - npm run build
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
