
language: node_js
node_js:
    - "stable"
install:
    - npm install
addons:
    code_climate:
        repo_token: qq7t2Ai/W2/yiJVyUOlGd48LK7zM4qub5I7St1nmBuyb5rToaL3sR/QSPKNKOIjK4g+bMTYkOxSVt+so7YnJqncTYoUGHsQP+R0wov5E4vVNbstdMCEvU4PfyQy+1QhJDJqqwhsCXSdJPB7+gb/LLN7ID2Cxe4XqRh9Igog463G7szILnYw/E22/jpMj+bcfh4mrY9z/JWONg/m7tXVD441Vq1lwvOVJqRt8wp3MppsJ9c4tPO8tTvvyPo8ZXsdZPzdZWPFZUJP+eoqQ8qoVBWrd39Q8+KRa43ViwhNtRLXlfgTHzzrSYBIddDK8RfOYR7+kmODXlkCQNw89jdmzLqJMyk0dGUjzXiu2qurRII3Fzh1PyPhXji/hQRl32YJX9hlGvxYYdqjYXWLUA3+sI+v9BF+9Za27juuOBCPPNCR9wv1rsr4LSELkpGY9YoaTuFu0zMiUOkyt1jxYnFyEHgAslgzquZ+oxxYXsm1x1egucaWiVi2ATyHwvpQo23A/5NG6Wzr/C4aQEfiuuv2KM9LbtANR1sMT49m4kZ7wJmnElEw86i0gtaqyGW+WHlaL0nIUI3eMDwtb+Qf/jwJwC80PTg/8sDIt8bXYWdXKpe3FMf3Q8YLKqNAln/EB+5kxPfQGXQY+jIlJsb8L1YFYEUbKvmOVu7O7iSDw6/g2p2A=
script:
    - npm run coveralls
before_script:
  - npm install codeclimate-test-reporter istanbul -g
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
