
language: node_js
node_js:
    - "stable"
install:
    - npm install
addons:
    code_climate:
        repo_token: 5a5b19118fbe960744b7d05bc448caf3dd89c692
script:
    - npm run coveralls
before_script:
  - npm install codeclimate-test-reporter istanbul -g
  - npm run build
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
